name: firstGHAction
on: 
  push:
    branches:
      - main
jobs:
  first-job: 
    name: firstTask
    runs-on: ubuntu-latest
    steps:
      - name: run bash command Before
        run: ls
        shell: bash
      - name: run Checkout like git clone <my-repo>
        uses: action/checkout@v3
      - name: run bash After command
        run: ls
        shell: bash